# This file is part of the Astrometry.net suite.
# Licensed under a 3-clause BSD style license - see LICENSE
include $(COMMON)/makefile.cross
NETPBM_INC ?= $(shell $(PKG_CONFIG) --exists netpbm && $(PKG_CONFIG) --cflags netpbm || echo)
NETPBM_LIB ?= $(shell $(PKG_CONFIG) --exists netpbm && $(PKG_CONFIG) --libs netpbm || echo "-L. -lnetpbm")
